### ISSUE TITLE
兆能M2升级新固件ipv6没法连接

### ISSUE THREAD

**Issue by 0weianun** [sdf8057/cloudbuild#10]
嗨！作者您好；
        设备兆能M2，使用：openwrt-ipq60xx-generic-cmiot_ax18-squashfs-nand-sysupgrade，不保留配置升级，发现ipv6没法访问（固件默认：禁止解析 IPv6 DNS 记录是关闭状态呀）我上一个固件也是使用您仓库云编译，可以正常访问ipv6。这次我看你有直接发布的就直接升级了。请问一下还是需要设置其他地方的吗？我对ipv6有远程连接需求希望可以回复了一下，可以解决就最好了。

**Comment by 0weianun** [comment]
什么配置都没有改，就PPPoE拨号上网。IPv6 WAN 状态显示获取到了地址和dns。LAN口IPV6设置默认服务器模式，但是电脑和手机都无法分发公网IPV6，却换中继模式也没有反应，我看etc/config/dhcp也确实有修改。折腾了一会，解决不了，准备回滚10月份那个版本😞

**Comment by sdf8057** [comment]
没动过ipv6相关代码

**Comment by 0weianun** [comment]
> 没动过IPv6相关代码

今早从uboot刷写固件，已经成功连接上了IPV6（默认设置，刚拨号成功就获取到了）

**Comment by 0weianun** [comment]
> 你都改成混合模式，另一个是有序+无序，默认通告关掉，ULA 前缀删掉，防火墙里默认dhcp那些不要动

默认设置获取到了，谢谢您回复
