### ISSUE TITLE
NAT回环仍然有bug

### ISSUE THREAD

**Issue by xyzeratul** [sdf8057/cloudbuild#26]
ZN-M2，4.4.60，ipq6000_2023.05.09-2210版本：

NAT 回环选上后不起作用，后面手动在sysctl.conf里面添加：
```
net.bridge.bridge-nf-call-arptables=0
net.bridge.bridge-nf-call-ip6tables=0
net.bridge.bridge-nf-call-iptables=0
```
重启sysctl服务后才正常，不知道是哪里出问题了

**Comment by sdf8057** [comment]
我没这问题，也许是你用openclash有冲突

**Comment by xyzeratul** [comment]
> 我没这问题，也许是你用openclash有冲突

我没有使用openclash，也没有使用任何VPN插件

**Comment by tanst** [comment]
我也有这个问题，按楼主方法手动添加后解决了。
还有一个问题，过一段时间访问：【系统】-【启动项】直接卡死了
路径：/cgi-bin/luci/admin/system/startup
