### ISSUE TITLE
ipq6000想编译带wifi的

### ISSUE THREAD

**Issue by monkeybape** [sdf8057/cloudbuild#27]
很早之前编辑wifi可以使用，但是最新的似乎编译wifi，和之前一样选择了gl-ax1800后，添加选择了ath11k-wifi-gl-ax1800，以及kmod-ath11k后然后build后，刷入系统还是没有wifi，请问大佬还需要增加哪些wifi相关的。

**Comment by sdf8057** [comment]
你还需要回退cadec00f4b a2c62d782d这两个提交

**Comment by monkeybape** [comment]
Download failed.
No more mirrors to try - giving up.
Checking out files from the git repository...
Cloning into 'qca-ssdk-shell-2021-01-27-5661366d'...
fatal: unable to access 'https://source.codeaurora.org/quic/qsdk/oss/ssdk-shell/': Could not resolve host: source.codeaurora.org
好像很多源都失效了

**Comment by monkeybape** [comment]
> 你还需要回退cadec00f4b a2c62d782d这两个提交

回退了 重新build把dl补齐后，还是没有wifi.

**Comment by monkeybape** [comment]
> 你还需要回退cadec00f4b a2c62d782d这两个提交

大佬 似乎这个两个回退 分别回退后build也是没有wifi，能再看看吗？
