### ISSUE TITLE
udp端口转发不成功

### ISSUE THREAD

**Issue by ws245909346** [sdf8057/cloudbuild#28]
云编译或者本地编译的固件均出现udp端口转发不成功，不管是用防火墙里的还是socat，tcp转发正常，有谁遇到过吗？如何解决？

**Comment by sdf8057** [comment]
不编译nss相关组件试试

**Comment by ws245909346** [comment]
> 不编译nss相关组件试试

去除后编译了好多回均不成功，可能是自定义的插件问题？熬了几个晚上，最后都是227错误。
我还是用回去年的版本吧，不折腾了，非常感谢大神回复。

**Comment by bequt** [comment]
> > 不编译nss相关组件试试
> 
> 去除后编译了好多回均不成功，可能是自定义的插件问题？熬了几个晚上，最后都是227错误。 我还是用回去年的版本吧，不折腾了，非常感谢大神回复。

用的是哪个版本啊？有链接吗？
