### ISSUE TITLE
请问itb后缀的文件怎么刷？

### ISSUE THREAD

**Issue by tonyk520** [sdf8057/cloudbuild#37]
您好，
我知道
...-squashfs-nand-factory.ubi可以在uboot刷，
...-squashfs-nand-sysupgrade.bin可以直接在刷好的OP系统里升级用，
可没搞明白
...-initramfs-fit-uImage.itb这个怎么刷？看名称是直接初始化分区的，可是大小和完整固件差不多啊

**Comment by refined-fish** [comment]
这个东西不用管，目前似乎没有软件支持刷他
