### ISSUE TITLE
设备：ZN-M2，在更换为1G的内存后，cpufreq 调节里面没有1200000这个档位了

### ISSUE THREAD

**Issue by BaeKey** [sdf8057/cloudbuild#9]
不希望超频使用，但是现在默认的只有3个档位，不知道问题出在哪里
![Snipaste_2022-12-29_18-39-40](https://user-images.githubusercontent.com/66151005/209940115-eb200fbe-03ed-42e4-b711-ff9d1a205fab.jpg)

**Comment by BaeKey** [comment]
> 



> 跟你换内存没关系
> 
> [sdf8057/ipq6000@1ae577c](https://github.com/sdf8057/ipq6000/commit/1ae577c37738b69cf7802b415797bbbccf553782) 看这个

知道了，谢谢指导

**Comment by sdf8057** [comment]
真奇怪，我试了在360v6上面会自动补全中间的那几个频率，没想到和目不会。
